### ISSUE TITLE
Fix für STATS$IDLE_EVENT

### ISSUE THREAD

**Issue by oraculix** [Rendanic/SQL-Zauberkasten#7]
(statspack_create.sql): Für das Problem mit den Idle Events gibt es einen Patch: Bug# [18284201.8](https://support.oracle.com/epmos/faces/DocContentDisplay?id=18284201.8)

Da viele Kunden allerdings keine One-Off-Patches einspielen und da Oracle dieser Fehler in der Vergangenheit schon mehrfach unterlaufen ist, verbleibt das im Status "wontfix".

**Comment by Rendanic** [comment]
Das Problem wurde zwischenzeitlich im SQL-Zauberkasten gelöst.
